### ISSUE TITLE
[Client] main__header contents / CSS 적용

### ISSUE THREAD

**Issue by Hal-ang** [codestates/soundWave_Client#10]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 소스에 맞는 조건부 css 처리 적용
2. [x] 가로등 css 효과 주기 (불빛, 깜빡임, 움직임)
3. [x] 자동차 css 효과 주기 (바운스, 움직임)
4. [x] 도로 css 효과 주기 (움직임)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `Middle`
