### ISSUE TITLE
[Client] 사이드 바 내 그룹 저장 컴포넌트 생성 및 구현 

### ISSUE THREAD

**Issue by Hal-ang** [codestates/soundWave_Client#19]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 저장 버튼 구현
2. [x] 그룹이름 인풋 구현
3. [x] 날씨 선택 기능 구현
4. [x] css 적용

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
