### ISSUE TITLE
[Client] 사이드바 내 history 컴포넌트 기능 구현

### ISSUE THREAD

**Issue by Hal-ang** [codestates/soundWave_Client#22]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 그룹 삭제 기능 
2. [x] others history 목록 확인
3. [x] my history 목록 확인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint3`
- Urgency: `High`
