### ISSUE TITLE
[Client] About 컴포넌트 생성, 실행 장면 gif 파일 제작 및 기본 레이아웃 설정

### ISSUE THREAD

**Issue by Hal-ang** [codestates/soundWave_Client#28]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 

### TODO
1. [ ] main 내 about 버튼 구현
2. [ ] 주요 기능 gif 제작
3. [ ] 기본 레이아웃 구성

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint3`
- Urgency: `High`
